## Computational Methods - Homework 6
### Universidad de Antioquia

**Student:** Andrés Felipe Riaño Quintanilla

**ID:** 1083928808 

Consider a circuit:
<img src="imgs/homework_circuit.png" width="700" />

The set of linear equations comes from the Kirchhoff's rules (in case of doubts review the literature)

Find the currents $I_1 \cdots I_6$ knowing that the 

Resistances are:

$R_1=1 \Omega$,
$R_2=2 \Omega$,
$R_3=3 \Omega$,
$R_4=4 \Omega$,
$R_5=5 \Omega$

Voltages are:
$E_1=10 V$,
$E_2=40 V$

### Matrix equation

$$RI=E$$

$$\begin{bmatrix}{-R_1}&{-R_2}&{-R_3}&{0}&{0}&{0}\\{0}&{R_2}&{0}&{-R_4}&{0}&{0}\\{0}&{0}&{R_3}&{0}&{-R_5}&{0}\\{1}&{0}&{-1}&{0}&{-1}&{0}\\{-1}&{1}&{0}&{1}&{0}&{0}\\{0}&{0}&{0}&{-1}&{1}&{1}\end{bmatrix} \begin{bmatrix}{I_1}\\{I_2}\\{I_3}\\{I_4}\\{I_5}\\{I_6}\end{bmatrix}=\begin{bmatrix}{-E_1}\\{-E_2}\\{E_2}\\{0}\\{0}\\{0}\end{bmatrix}$$

$$\begin{bmatrix}{-1}&{-2}&{-3}&{0}&{0}&{0}\\{0}&{2}&{0}&{-4}&{0}&{0}\\{0}&{0}&{3}&{0}&{-5}&{0}\\{1}&{0}&{-1}&{0}&{-1}&{0}\\{-1}&{1}&{0}&{1}&{0}&{0}\\{0}&{0}&{0}&{-1}&{1}&{1}\end{bmatrix} \begin{bmatrix}{I_1}\\{I_2}\\{I_3}\\{I_4}\\{I_5}\\{I_6}\end{bmatrix}=\begin{bmatrix}{-10}\\{-40}\\{40}\\{0}\\{0}\\{0}\end{bmatrix}$$

In [1]:
import numpy as np

In [2]:
R=np.array([[-1,-2,-3,0,0,0],[0,2,0,-4,0,0],[0,0,3,0,-5,0],[1,0,-1,0,-1,0],[-1,1,0,1,0,0],[0,0,0,-1,1,1]])
E=np.array([[-10],[-40],[40],[0],[0],[0]])
print('R = \n{} \n\nE = \n{}'.format(R,E))

R = 
[[-1 -2 -3  0  0  0]
 [ 0  2  0 -4  0  0]
 [ 0  0  3  0 -5  0]
 [ 1  0 -1  0 -1  0]
 [-1  1  0  1  0  0]
 [ 0  0  0 -1  1  1]] 

E = 
[[-10]
 [-40]
 [ 40]
 [  0]
 [  0]
 [  0]]


In [3]:
#Solving the matrix equation

I=np.linalg.solve(R, E)
print('I = \n{} \n'.format(I))

for i in range(len(I)):
    print('I_{} = {} A. \n'.format(i+1,I[i][0]))

I = 
[[ 1.98019802]
 [-5.34653465]
 [ 6.23762376]
 [ 7.32673267]
 [-4.25742574]
 [11.58415842]] 

I_1 = 1.9801980198019802 A. 

I_2 = -5.346534653465347 A. 

I_3 = 6.237623762376238 A. 

I_4 = 7.326732673267327 A. 

I_5 = -4.257425742574258 A. 

I_6 = 11.584158415841586 A. 

