# Computational Methods - Homework 7
## Universidad de Antioquia

**Student:** Andrés Felipe Riaño Quintanilla

**ID:** 1083928808 

Calculate $S^5$ using two methods. in a "for" loop and using diagonalization. Compare the results.

$$S=
\begin{bmatrix}
1 &  -1 & -1 & -1\\
-1 &  2 & 0 & 0\\
-1 &  3 & 3 & 0 \\
-1 &  0 & 1 & 4 \\
\end{bmatrix}$$

**Defining S:**

In [6]:
import numpy as np

S = np.array([[1,-1,-1,-1],[-1,2,0,0],[-1,3,3,0],[-1,0,1,4]])

**$S^5$ using a "for" loop:** 

In [5]:
S5f = np.identity(len(S))

for i in range(5):
    
    S5f = np.matmul(S5f,S)

print("S^5 using a 'for' loop: \n\n{}".format(S5f))

S^5 using a 'for' loop: 

[[  485.  -755.  -563.  -563.]
 [ -179.   280.   192.   192.]
 [ -675.  1201.   707.   464.]
 [-1027.  1448.  1275.  1518.]]


**$S^5$ using diagonalization:**

$$S^5=PD^5P^{-1}$$

In [13]:
E_val, E_vec = np.linalg.eig(S)  #Eigen values and eigen vectors.
P = E_vec  
Pinv = np.linalg.inv(P)
D5 = np.zeros((len(S),len(S)))

for i in range(len(S)):
    D5[i,i] = (E_val[i])**5
    
print('P = \n{}'.format(P))
print('\nD = \n{}'.format(D))

P = 
[[-3.49561271e-01  7.94033408e-01  7.62229110e-02  7.27025315e-16]
 [ 1.21959906e-01  4.79650284e-01  3.61664456e-01  6.86635020e-16]
 [ 3.83368157e-01 -2.42866291e-01 -8.33174113e-01 -7.07106781e-01]
 [ 8.46145115e-01  2.83659156e-01  4.11351172e-01  7.07106781e-01]]

D = 
[[4.86619826 0.         0.         0.        ]
 [0.         0.34455762 0.         0.        ]
 [0.         0.         1.78924412 0.        ]
 [0.         0.         0.         3.        ]]


In [19]:
S5d = np.matmul(P,np.matmul(D5,Pinv))

print("S^5 using diagonalization: \n\n{}".format(S5d))

S^5 using diagonalization: 

[[  485.  -755.  -563.  -563.]
 [ -179.   280.   192.   192.]
 [ -675.  1201.   707.   464.]
 [-1027.  1448.  1275.  1518.]]


It seems that the results of using a "for" loop and using diagonalization were the same. But they are different in some decimal places:

In [30]:
print(S5f-S5d)

[[ 5.68434189e-13 -9.09494702e-13 -1.02318154e-12 -1.13686838e-13]
 [ 2.27373675e-13 -1.70530257e-13 -1.98951966e-13 -8.52651283e-13]
 [-4.54747351e-13  9.09494702e-13  9.09494702e-13 -5.68434189e-13]
 [ 1.13686838e-12 -1.13686838e-12 -6.82121026e-13 -2.50111043e-12]]


The above matrix entries are approximately zero.