In [1]:
import numpy as np

In [7]:
#Matriz aumentada
A = np.array( [[ -1 ,-2, -3, 0, 0, 0],
                [0 , 2, 0, -4, 0, 0],
                [0 , 0, 3, 0, -5, 0],
                [1, 0, -1, 0, -1, 0],
                [-1, 1, 0, 1, 0, 0 ],
                [0, 0, 0, -1, 1, 1 ]] )
print(f"A = {A}")

b = np.array([[-10],
             [-40],
             [40],
             [0],
             [0],
             [0]])

print(f"b = {b}")

A = [[-1 -2 -3  0  0  0]
 [ 0  2  0 -4  0  0]
 [ 0  0  3  0 -5  0]
 [ 1  0 -1  0 -1  0]
 [-1  1  0  1  0  0]
 [ 0  0  0 -1  1  1]]
b = [[-10]
 [-40]
 [ 40]
 [  0]
 [  0]
 [  0]]


In [8]:
#Solving the equations:
x=np.linalg.solve(A, b)
print(x)

[[ 1.98019802]
 [-5.34653465]
 [ 6.23762376]
 [ 7.32673267]
 [-4.25742574]
 [11.58415842]]
