In [54]:
import numpy as np # Importamos numpy.

In [55]:
a=[[1,-1,-1,-1],[ -1,2,0,0],[-1,3,3,0],[-1,0,1,4]]  # Tenemos nuestra matriz





In [56]:
# Realizacion de la tarea:
def multiplicacion(a,n):
    n -= 1
    h=a.copy()              # Realizamos el for correspondiente.
    for i in range(n):
        h=np.matmul(a,h)
    return h    
    





In [57]:
multiplicacion(a,5)  # Evaluamos en 5.

array([[  485,  -755,  -563,  -563],
       [ -179,   280,   192,   192],
       [ -675,  1201,   707,   464],
       [-1027,  1448,  1275,  1518]])

In [58]:
multiplicacion(a,5)  # Tenemos la multiplicacion
resultd = np.linalg.matrix_power(a, 5) # Esta es otra manera para saber si nuestro resultado es correcto
print(resultd) # Imprimimos la matriz.

[[  485  -755  -563  -563]
 [ -179   280   192   192]
 [ -675  1201   707   464]
 [-1027  1448  1275  1518]]


In [59]:
# Veamos co# Lets check all those operations

deta=np.linalg.det(a)    # Miramos si el determinante es distinto de cero
print('deta=\n',deta)

evalues, evectors = np.linalg.eig(a)  # Obtenemos los eigenvectores, y eigenvalores.
print(np.prod(evalues))  # Vemos el producto de los egenvalores el det de A
print(evectors)



deta=
 8.999999999999998
8.999999999999988
[[-3.49561271e-01  7.94033408e-01  7.62229110e-02  7.27025315e-16]
 [ 1.21959906e-01  4.79650284e-01  3.61664456e-01  6.86635020e-16]
 [ 3.83368157e-01 -2.42866291e-01 -8.33174113e-01 -7.07106781e-01]
 [ 8.46145115e-01  2.83659156e-01  4.11351172e-01  7.07106781e-01]]


In [60]:
P = evectors  # Eigenvectores.
Pinv=np.linalg.inv(P) # Inversa de eigenvectores.

D = np.zeros((4,4))
for i in range(4):         # D
    D[i,i] = evalues[i]

print(D)
resultd = np.linalg.matrix_power(D, 5)  # ELEVAMOS d a 5
print(resultd)

print('pD^5p^-1=\n',np.matmul(P,np.matmul(resultd,Pinv))) # Obtenemos el resultado


[[4.86619826 0.         0.         0.        ]
 [0.         0.34455762 0.         0.        ]
 [0.         0.         1.78924412 0.        ]
 [0.         0.         0.         3.        ]]
[[2.72865731e+03 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.85634224e-03 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.83378321e+01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.43000000e+02]]
pD^5p^-1=
 [[  485.  -755.  -563.  -563.]
 [ -179.   280.   192.   192.]
 [ -675.  1201.   707.   464.]
 [-1027.  1448.  1275.  1518.]]
