## Homework 7: Linear Algebra 03

In [1]:
import numpy as np

In [2]:
#Matrix
S = np.array([[1,-1,-1,-1],
             [-1, 2, 0, 0],
             [-1, 3, 3, 0],
             [-1, 0, 1, 4]])

#Eigenvector and eigenvalues
evals , evect = np.linalg.eig(S)
print(evals, "\n", evect)

[4.86619826 0.34455762 1.78924412 3.        ] 
 [[-3.49561271e-01  7.94033408e-01  7.62229110e-02  7.27025315e-16]
 [ 1.21959906e-01  4.79650284e-01  3.61664456e-01  6.86635020e-16]
 [ 3.83368157e-01 -2.42866291e-01 -8.33174113e-01 -7.07106781e-01]
 [ 8.46145115e-01  2.83659156e-01  4.11351172e-01  7.07106781e-01]]


Calculate $S^5$ using two methods. in a "for" loop and using diagonalization. Compare the results.

In [3]:
#Using Diagonalization
P = evect
Pinv = np.linalg.inv(P)
D_5 = np.zeros((4,4))

for i in range(4):
    D_5[i,i] = evals[i]**5

S_5 = np.matmul(np.matmul(P, D_5), Pinv)
print(" S^5 using diagonalization : \n {}".format(S_5))

 S^5 using diagonalization : 
 [[  485.  -755.  -563.  -563.]
 [ -179.   280.   192.   192.]
 [ -675.  1201.   707.   464.]
 [-1027.  1448.  1275.  1518.]]


In [4]:
# Loop

A = np.copy(S)

for i in range(1,5):
    A = np.matmul(S, A)
      
print("S^5 using a loop : \n {}".format(A))

S^5 using a loop : 
 [[  485  -755  -563  -563]
 [ -179   280   192   192]
 [ -675  1201   707   464]
 [-1027  1448  1275  1518]]


We get the same result with both methods. 